server:
  port: 8080
spring:
  application:
    name: common-note-api
  profiles:
    active: local
  jpa:  #설정을 해주어야 Table 생성됨
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true    #쿼리문 보이도록 설정
        format_sql: true  #SQL문 포맷 규격화
