server:
  port: 8080
spring:
  application:
    name: common-note-api
  profiles:
    active: local
  jpa:  #설정을 해주어야 Table 생성됨
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true    #쿼리문 보이도록 설정
        format_sql: true  #SQL문 포맷 규격화
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  secret: a2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ==
  token-validity-in-seconds: 86400 # ttl (초)